### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by orzarchi** [hnrlee/vcl_extension#5]
Hey,
Great work!
I did some work on creating a Lexer/Tokenizer for VCL, which allowed me to create a typescript-based code formatter.
Let me know if you're still working on this project and want to incorporate my work.
If so, I can publish it as a package for you to use.

**Comment by orzarchi** [comment]
@hnrlee

**Comment by hnrlee** [comment]
Hello orzarchi,
Thanks for the offer to help! Based on what I see in your VCL extension repo though, it seems that my extension already covers everything your extension does, so there would be no additional functionality.

**Comment by orzarchi** [comment]
Hi,
I still haven't made my code public.
I'll try getting to it soon.
I made a lexer/parser in typescript and used it to create a code formatter.

**Comment by orzarchi** [comment]
Okay, I finally got around to it @hnrlee 
https://github.com/orzarchi/vcl-tools
It includes a basic pretty printer, and a complete VCL AST and related tools. I planned to use it to extend the language and create some sort of easier to program "super-vcl", but I didn't get around to it.

Let me know what you think, feel free to contact me whenever you want.

**Comment by hnrlee** [comment]
Hey Orzarchi, I'm thinking you might want to publish that as a separate extension. It seems that you already have it ready to go. It looks great though, I'd love to try it out!
